# Using Yahoo Finance API

In [1]:
import yfinance as yahooFinance

In [2]:
googleinfo = yahooFinance.Ticker("GOOGL")

In [4]:
print(googleinfo.info)

{'address1': '1600 Amphitheatre Parkway', 'city': 'Mountain View', 'state': 'CA', 'zip': '94043', 'country': 'United States', 'phone': '650 253 0000', 'website': 'https://www.abc.xyz', 'industry': 'Internet Content & Information', 'industryKey': 'internet-content-information', 'industryDisp': 'Internet Content & Information', 'sector': 'Communication Services', 'sectorKey': 'communication-services', 'sectorDisp': 'Communication Services', 'longBusinessSummary': 'Alphabet Inc. offers various products and platforms in the United States, Europe, the Middle East, Africa, the Asia-Pacific, Canada, and Latin America. It operates through Google Services, Google Cloud, and Other Bets segments. The Google Services segment provides products and services, including ads, Android, Chrome, hardware, Gmail, Google Drive, Google Maps, Google Photos, Google Play, Search, and YouTube. It is also involved in the sale of apps and in-app purchases and digital content in the Google Play store; and Fitbit wearable devices, Google Nest home products, Pixel phones, and other devices, as well as in the provision of YouTube non-advertising services. The Google Cloud segment offers infrastructure, cybersecurity, data, analytics, AI, and machine learning, and other services; Google Workspace that include cloud-based collaboration tools for enterprises, such as Gmail, Docs, Drive, Calendar, and Meet; and other services for enterprise customers. The Other Bets segment sells health technology and internet services. The company was founded in 1998 and is headquartered in Mountain View, California.', 'fullTimeEmployees': 182381, 'companyOfficers': [{'maxAge': 1, 'name': 'Mr. Sundar  Pichai', 'age': 50, 'title': 'CEO & Director', 'yearBorn': 1973, 'fiscalYear': 2022, 'totalPay': 7947461, 'exercisedValue': 39618220, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Ruth M. Porat', 'age': 65, 'title': 'President, Chief Investment Officer, Senior VP & CFO', 'yearBorn': 1958, 'fiscalYear': 2022, 'totalPay': 1790046, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Lawrence Edward Page', 'age': 50, 'title': 'Co-Founder & Director', 'yearBorn': 1973, 'fiscalYear': 2022, 'totalPay': 1, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Sergey  Brin', 'age': 49, 'title': 'Co-Founder & Director', 'yearBorn': 1974, 'fiscalYear': 2022, 'totalPay': 1, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. J. Kent Walker', 'age': 62, 'title': 'President of Global Affairs, Chief Legal Officer & Company Secretary', 'yearBorn': 1961, 'fiscalYear': 2022, 'totalPay': 1787541, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Dr. Prabhakar  Raghavan', 'age': 62, 'title': 'Senior Vice President of Knowledge and Information - Google', 'yearBorn': 1961, 'fiscalYear': 2022, 'totalPay': 1785329, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Philipp  Schindler', 'age': 51, 'title': 'Senior Vice President & Chief Business Officer of Google', 'yearBorn': 1972, 'fiscalYear': 2022, 'totalPay': 1785814, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': "Ms. Amie Thuener O'Toole", 'age': 48, 'title': 'Chief Accounting Officer & VP', 'yearBorn': 1975, 'fiscalYear': 2022, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Ellen  West', 'title': 'Vice President of Investor Relations', 'fiscalYear': 2022, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Fiona Clare Cicconi', 'age': 57, 'title': 'Chief People Officer', 'yearBorn': 1966, 'fiscalYear': 2022, 'exercisedValue': 0, 'unexercisedValue': 0}], 'auditRisk': 8, 'boardRisk': 2, 'compensationRisk': 10, 'shareHolderRightsRisk': 10, 'overallRisk': 10, 'governanceEpochDate': 1706400000, 'compensationAsOfEpochDate': 1672444800, 'maxAge': 86400, 'priceHint': 2, 'previousClose': 152.185, 'open': 152.06, 'dayLow': 151.43, 'dayHigh': 153.78, 'regularMarketPreviousClose': 152.185, 'regularMarketOpen': 152.06, 'regularMarketDayLow': 151.43, 'regularMarketDayHigh': 153.78, 'beta': 1.054, 'trailingPE': 29.408047, 'forwardPE': 24.799675, 'volume': 27657003, 'regularMarketVolume': 27657003, 'averageVolume': 27114609, 'averageVolume10days': 26474750, 'averageDailyVolume10Day': 26474750, 'bid': 153.45, 'ask': 153.54, 'bidSize': 900, 'askSize': 1300, 'marketCap': 1928622768128, 'fiftyTwoWeekLow': 88.58, 'fiftyTwoWeekHigh': 153.78, 'priceToSalesTrailing12Months': 6.4907947, 'fiftyDayAverage': 138.7402, 'twoHundredDayAverage': 128.7065, 'currency': 'USD', 'enterpriseValue': 1831842217984, 'profitMargins': 0.22459, 'floatShares': 11177038320, 'sharesOutstanding': 5918000128, 'sharesShort': 48701781, 'sharesShortPriorMonth': 49918340, 'sharesShortPreviousMonthDate': 1702598400, 'dateShortInterest': 1705017600, 'sharesPercentSharesOut': 0.0039, 'heldPercentInsiders': 0.0027599998, 'heldPercentInstitutions': 0.79791, 'shortRatio': 1.82, 'shortPercentOfFloat': 0.0082, 'impliedSharesOutstanding': 12563500032, 'bookValue': 21.785, 'priceToBook': 7.0465913, 'lastFiscalYearEnd': 1672444800, 'nextFiscalYearEnd': 1703980800, 'mostRecentQuarter': 1696032000, 'earningsQuarterlyGrowth': 0.415, 'netIncomeToCommon': 66731999232, 'trailingEps': 5.22, 'forwardEps': 6.19, 'pegRatio': 1.65, 'lastSplitFactor': '20:1', 'lastSplitDate': 1658102400, 'enterpriseToRevenue': 6.165, 'enterpriseToEbitda': 19.068, '52WeekChange': 0.5531162, 'SandP52WeekChange': 0.20883334, 'exchange': 'NMS', 'quoteType': 'EQUITY', 'symbol': 'GOOGL', 'underlyingSymbol': 'GOOGL', 'shortName': 'Alphabet Inc.', 'longName': 'Alphabet Inc.', 'firstTradeDateEpochUtc': 1092922200, 'timeZoneFullName': 'America/New_York', 'timeZoneShortName': 'EST', 'uuid': 'e15ce71f-f533-3912-9f11-a46c09e2412b', 'messageBoardId': 'finmb_29096', 'gmtOffSetMilliseconds': -18000000, 'currentPrice': 153.51, 'targetHighPrice': 166.0, 'targetLowPrice': 117.91, 'targetMeanPrice': 144.34, 'targetMedianPrice': 143.4, 'recommendationMean': 1.9, 'recommendationKey': 'buy', 'numberOfAnalystOpinions': 44, 'totalCash': 119935000576, 'totalCashPerShare': 9.583, 'ebitda': 96071000064, 'totalDebt': 30446000128, 'quickRatio': 1.865, 'currentRatio': 2.043, 'totalRevenue': 297131999232, 'debtToEquity': 11.144, 'revenuePerShare': 23.337, 'returnOnAssets': 0.13492, 'returnOnEquity': 0.25334, 'freeCashflow': 70757122048, 'operatingCashflow': 106444996608, 'earningsGrowth': 0.46, 'revenueGrowth': 0.11, 'grossMargins': 0.56122, 'ebitdaMargins': 0.32333001, 'operatingMargins': 0.27962, 'financialCurrency': 'USD', 'trailingPegRatio': 1.4478}

In [5]:
infod = googleinfo.info
infod["zip"]

'94043'

In [6]:
for k, v in infod.items():
    print(k, ":", v)

address1 : 1600 Amphitheatre Parkway
city : Mountain View
state : CA
zip : 94043
country : United States
phone : 650 253 0000
website : https://www.abc.xyz
industry : Internet Content & Information
industryKey : internet-content-information
industryDisp : Internet Content & Information
sector : Communication Services
sectorKey : communication-services
sectorDisp : Communication Services
longBusinessSummary : Alphabet Inc. offers various products and platforms in the United States, Europe, the Middle East, Africa, the Asia-Pacific, Canada, and Latin America. It operates through Google Services, Google Cloud, and Other Bets segments. The Google Services segment provides products and services, including ads, Android, Chrome, hardware, Gmail, Google Drive, Google Maps, Google Photos, Google Play, Search, and YouTube. It is also involved in the sale of apps and in-app purchases and digital content in the Google Play store; and Fitbit wearable devices, Google Nest home products, Pixel phones, and other devices, as well as in the provision of YouTube non-advertising services. The Google Cloud segment offers infrastructure, cybersecurity, data, analytics, AI, and machine learning, and other services; Google Workspace that include cloud-based collaboration tools for enterprises, such as Gmail, Docs, Drive, Calendar, and Meet; and other services for enterprise customers. The Other Bets segment sells health technology and internet services. The company was founded in 1998 and is headquartered in Mountain View, California.
fullTimeEmployees : 182381
companyOfficers : [{'maxAge': 1, 'name': 'Mr. Sundar  Pichai', 'age': 50, 'title': 'CEO & Director', 'yearBorn': 1973, 'fiscalYear': 2022, 'totalPay': 7947461, 'exercisedValue': 39618220, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Ruth M. Porat', 'age': 65, 'title': 'President, Chief Investment Officer, Senior VP & CFO', 'yearBorn': 1958, 'fiscalYear': 2022, 'totalPay': 1790046, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Lawrence Edward Page', 'age': 50, 'title': 'Co-Founder & Director', 'yearBorn': 1973, 'fiscalYear': 2022, 'totalPay': 1, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Sergey  Brin', 'age': 49, 'title': 'Co-Founder & Director', 'yearBorn': 1974, 'fiscalYear': 2022, 'totalPay': 1, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. J. Kent Walker', 'age': 62, 'title': 'President of Global Affairs, Chief Legal Officer & Company Secretary', 'yearBorn': 1961, 'fiscalYear': 2022, 'totalPay': 1787541, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Dr. Prabhakar  Raghavan', 'age': 62, 'title': 'Senior Vice President of Knowledge and Information - Google', 'yearBorn': 1961, 'fiscalYear': 2022, 'totalPay': 1785329, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Philipp  Schindler', 'age': 51, 'title': 'Senior Vice President & Chief Business Officer of Google', 'yearBorn': 1972, 'fiscalYear': 2022, 'totalPay': 1785814, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': "Ms. Amie Thuener O'Toole", 'age': 48, 'title': 'Chief Accounting Officer & VP', 'yearBorn': 1975, 'fiscalYear': 2022, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Ellen  West', 'title': 'Vice President of Investor Relations', 'fiscalYear': 2022, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Fiona Clare Cicconi', 'age': 57, 'title': 'Chief People Officer', 'yearBorn': 1966, 'fiscalYear': 2022, 'exercisedValue': 0, 'unexercisedValue': 0}]
auditRisk : 8
boardRisk : 2
compensationRisk : 10
shareHolderRightsRisk : 10
overallRisk : 10
governanceEpochDate : 1706400000
compensationAsOfEpochDate : 1672444800
maxAge : 86400
priceHint : 2
previousClose : 152.185
open : 152.06
dayLow : 151.43
dayHigh : 153.78
regularMarketPreviousClose : 152.185
regularMarketOpen : 152.06
regularMarketDayLow : 151.43
regularMarketDayHigh : 153.78
beta : 1.054
trailingPE : 29.408047
forwardPE : 24.799675
volume : 27657003
regularMarketVolume : 27657003
averageVolume : 27114609
averageVolume10days : 26474750
averageDailyVolume10Day : 26474750
bid : 153.45
ask : 153.54
bidSize : 900
askSize : 1300
marketCap : 1928622768128
fiftyTwoWeekLow : 88.58
fiftyTwoWeekHigh : 153.78
priceToSalesTrailing12Months : 6.4907947
fiftyDayAverage : 138.7402
twoHundredDayAverage : 128.7065
currency : USD
enterpriseValue : 1831842217984
profitMargins : 0.22459
floatShares : 11177038320
sharesOutstanding : 5918000128
sharesShort : 48701781
sharesShortPriorMonth : 49918340
sharesShortPreviousMonthDate : 1702598400
dateShortInterest : 1705017600
sharesPercentSharesOut : 0.0039
heldPercentInsiders : 0.0027599998
heldPercentInstitutions : 0.79791
shortRatio : 1.82
shortPercentOfFloat : 0.0082
impliedSharesOutstanding : 12563500032
bookValue : 21.785
priceToBook : 7.0465913
lastFiscalYearEnd : 1672444800
nextFiscalYearEnd : 1703980800
mostRecentQuarter : 1696032000
earningsQuarterlyGrowth : 0.415
netIncomeToCommon : 66731999232
trailingEps : 5.22
forwardEps : 6.19
pegRatio : 1.65
lastSplitFactor : 20:1
lastSplitDate : 1658102400
enterpriseToRevenue : 6.165
enterpriseToEbitda : 19.068
52WeekChange : 0.5531162
SandP52WeekChange : 0.20883334
exchange : NMS
quoteType : EQUITY
symbol : GOOGL
underlyingSymbol : GOOGL
shortName : Alphabet Inc.
longName : Alphabet Inc.
firstTradeDateEpochUtc : 1092922200
timeZoneFullName : America/New_York
timeZoneShortName : EST
uuid : e15ce71f-f533-3912-9f11-a46c09e2412b
messageBoardId : finmb_29096
gmtOffSetMilliseconds : -18000000
currentPrice : 153.51
targetHighPrice : 166.0
targetLowPrice : 117.91
targetMeanPrice : 144.34
targetMedianPrice : 143.4
recommendationMean : 1.9
recommendationKey : buy
numberOfAnalystOpinions : 44
totalCash : 119935000576
totalCashPerShare : 9.583
ebitda : 96071000064
totalDebt : 30446000128
quickRatio : 1.865
currentRatio : 2.043
totalRevenue : 297131999232
debtToEquity : 11.144
revenuePerShare : 23.337
returnOnAssets : 0.13492
returnOnEquity : 0.25334
freeCashflow : 70757122048
operatingCashflow : 106444996608
earningsGrowth : 0.46
revenueGrowth : 0.11
grossMargins : 0.56122
ebitdaMargins : 0.32333001
operatingMargins : 0.27962
financialCurrency : USD
trailingPegRatio : 1.4478

In [9]:
display(googleinfo.history(period = "max"))

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2004-08-19 00:00:00-04:00,2.502503,2.604104,2.401401,2.511011,893181924,0.0,0.0
2004-08-20 00:00:00-04:00,2.527778,2.729730,2.515015,2.710460,456686856,0.0,0.0
2004-08-23 00:00:00-04:00,2.771522,2.839840,2.728979,2.737738,365122512,0.0,0.0
2004-08-24 00:00:00-04:00,2.783784,2.792793,2.591842,2.624374,304946748,0.0,0.0
2004-08-25 00:00:00-04:00,2.626627,2.702703,2.599600,2.652653,183772044,0.0,0.0
...,...,...,...,...,...,...,...
2024-01-23 00:00:00-05:00,145.889999,147.179993,145.500000,147.039993,21636100,0.0,0.0
2024-01-24 00:00:00-05:00,148.539993,149.850006,148.100006,148.699997,25233500,0.0,0.0
2024-01-25 00:00:00-05:00,150.070007,153.050003,149.539993,151.869995,29149100,0.0,0.0
2024-01-26 00:00:00-05:00,151.100006,152.539993,151.009995,152.190002,26101000,0.0,0.0
2024-01-29 00:00:00-05:00,152.059998,153.779999,151.429993,153.509995,27741200,0.0,0.0

In [13]:
import datetime

start = datetime.datetime(2004, 10, 21)
end = datetime.datetime(2017, 9, 2)
display(googleinfo.history(start = start, end = end))

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2004-10-21 00:00:00-04:00,3.613614,3.757007,3.544044,3.738238,582996420,0.0,0.0
2004-10-22 00:00:00-04:00,4.267768,4.508759,4.106106,4.315065,1474200324,0.0,0.0
2004-10-25 00:00:00-04:00,4.414414,4.865616,4.318068,4.689690,1309257432,0.0,0.0
2004-10-26 00:00:00-04:00,4.663163,4.820821,4.504505,4.549550,891391716,0.0,0.0
2004-10-27 00:00:00-04:00,4.572573,4.742743,4.548799,4.653904,533725740,0.0,0.0
...,...,...,...,...,...,...,...
2017-08-28 00:00:00-04:00,46.594002,46.742500,46.305500,46.406502,20988000,0.0,0.0
2017-08-29 00:00:00-04:00,45.997501,46.909500,45.965500,46.787498,23172000,0.0,0.0
2017-08-30 00:00:00-04:00,46.783501,47.292999,46.702499,47.181499,22406000,0.0,0.0
2017-08-31 00:00:00-04:00,47.314999,47.860001,47.312500,47.762001,33866000,0.0,0.0
2017-09-01 00:00:00-04:00,47.873501,47.916500,47.514000,47.599499,20858000,0.0,0.0

In [16]:
df = yahooFinance.download("AMZN GOOGL", start = start, end = end, group_by = "ticker")
df

[*********************100%%**********************]  2 of 2 completed

Ticker          GOOGL                                                          \
Price            Open       High        Low      Close  Adj Close      Volume
Date
2004-10-21   3.613614   3.757007   3.544044   3.738238   3.738238   582996420
2004-10-22   4.267768   4.508759   4.106106   4.315065   4.315065  1474200324
2004-10-25   4.414414   4.865616   4.318068   4.689690   4.689690  1309257432
2004-10-26   4.663163   4.820821   4.504505   4.549550   4.549550   891391716
2004-10-27   4.572573   4.742743   4.548799   4.653904   4.653904   533725740
...               ...        ...        ...        ...        ...         ...
2017-08-28  46.594002  46.742500  46.305500  46.406502  46.406502    20988000
2017-08-29  45.997501  46.909500  45.965500  46.787498  46.787498    23172000
2017-08-30  46.783501  47.292999  46.702499  47.181499  47.181499    22406000
2017-08-31  47.314999  47.860001  47.312500  47.762001  47.762001    33866000
2017-09-01  47.873501  47.916500  47.514000  47.599499  47.599499    20858000

Ticker           AMZN
Price            Open       High        Low      Close  Adj Close     Volume
Date
2004-10-21   1.965000   2.009500   1.925000   1.973500   1.973500  384342000
2004-10-22   1.811000   1.840000   1.650000   1.730000   1.730000  670886000
2004-10-25   1.700000   1.720500   1.686000   1.698500   1.698500  210636000
2004-10-26   1.707500   1.713000   1.675500   1.691500   1.691500  194850000
2004-10-27   1.681500   1.731500   1.681000   1.711500   1.711500  181214000
...               ...        ...        ...        ...        ...        ...
2017-08-28  47.327000  47.650002  47.112499  47.300999  47.300999   51934000
2017-08-29  47.000000  47.799999  46.816502  47.702999  47.702999   57486000
2017-08-30  47.922001  48.470501  47.845501  48.379501  48.379501   58092000
2017-08-31  48.735001  49.049999  48.638000  49.029999  49.029999   66630000
2017-09-01  49.209999  49.224998  48.844002  48.912498  48.912498   50718000

[3240 rows x 12 columns]

In [18]:
df.to_csv("csv_google_amazon.csv")